### ISSUE TITLE
Fix dictionary gas counting

### ISSUE THREAD

**Issue by igaray** [lambdaclass/cairo_native#289]
This test: https://github.com/lambdaclass/cairo_native/blob/main/tests/tests/dict.rs#L26
is currently ignored due a gas mismatch between the cairo vm and cairo native version.
It is likely that the way the dictionary libfuncs implement gas counting is buggy. 

A general description of how libfuncs handle the gas wallet counter would be an excellent first output.

**Comment by greged93** [comment]
Hey @igaray can I have this one?

**Comment by greged93** [comment]
Hey @igaray, just an update, I was able to pinpoint where the issue in gas accounting occurs: during squashing of a dict, which happens I believe when a dict is dropped, a gas refund takes place in order to account for duplicate key access in the dict. 

The gas refund is compiled to casm [here](https://github.com/starkware-libs/cairo/blob/main/crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs#L167) with the constants defined for refund [here](https://github.com/starkware-libs/cairo/blob/main/crates/cairo-lang-sierra-gas/src/core_libfunc_cost_base.rs#L59).

In the case of the test you mentioned, the gas difference is of 4050 gas, which is due to the fact that the `insert` and the `read` both add the same key to the dictionary. This in turn causes a refund of `ConstCost { steps: 46, holes: 0, range_checks: 6 } - ConstCost { steps: 9, holes: 0, range_checks: 1 } = ConstCost { steps: 37, holes: 0, range_checks: 5 }` which gives a gas refund of 4050 (see [here](https://github.com/starkware-libs/cairo/blob/main/crates/cairo-lang-sierra-gas/src/objects.rs#L17) for cost computation).

Will let you know about my progress to add this refund in the `build_squash` function.

**Comment by igaray** [comment]
Incredible! Thanks for the update @greged93 !

**Comment by greged93** [comment]
hey @igaray, just to let you know the steps I plan to take to fix the gas and check with you what you think:
- Update the dict type from a llvm opaque_pointer to a llvm struct. First field would be to ptr to the dict and second the number of accesses to the dict.
- Add `cairo_native__dict_len` in order to retrieve at runtime the length of the dict.
- Update `build_squash` in order to refund the `gas_builtin` arg by `(accesses - dict_len) * DICT_SQUASH_UNIQUE_KEY_COST.cost() - DICT_SQUASH_REPEATED_ACCESS_COST.cost()`

Let me know what you think or if you see any issue with this

**Comment by edg-l** [comment]
> hey @igaray, just to let you know the steps I plan to take to fix the gas and check with you what you think:
> 
>     * Update the dict type from a llvm opaque_pointer to a llvm struct. First field would be to ptr to the dict and second the number of accesses to the dict.
> 
>     * Update `build_get` to increment the dict accesses field at each execution.
> 
>     * Add `cairo_native__dict_len` in order to retrieve at runtime the length of the dict.
> 
>     * Update `build_squash` in order to refund the `gas_builtin` arg by `(accesses - dict_len) * DICT_SQUASH_UNIQUE_KEY_COST.cost() - DICT_SQUASH_REPEATED_ACCESS_COST.cost()`
> 
> 
> Let me know what you think or if you see any issue with this

looks good
