### ISSUE TITLE
Failing test: ec_point_from_x_big

### ISSUE THREAD

**Issue by igaray** [lambdaclass/cairo_native#293]

**Comment by azteca1998** [comment]
I think the problem is in `ec_point_from_x_nz`. The VM's algorithm is implemented [here](https://github.com/starkware-libs/cairo/blob/c8f0da0c5053600fd6d4c2fd3aff8f79d1256fc5/crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs#L166-L241). Since we're using a library, said library may or may not implement the complete algorithm.

After testing some stuff I found that for the value in the failing test, at least the following condition isn't met:
```
    // Check that y < PRIME / 2 to enforce a deterministic behavior (otherwise, the prover can
    // choose either y or -y).
```
However, I think this would cause the libfunc to return `None` instead of a point, which is not the case in the VM.
