### ISSUE TITLE
Check if removed lifetime in SyscallHandlerMeta could cause issues

### ISSUE THREAD

**Issue by entropidelic** [lambdaclass/cairo_native#306]
This phantom field has been removed for avoiding lifetimes compiling errors when integrating with SiR. We should check if this could case problems in the future

```rust
pub struct SyscallHandlerMeta<'a> {
    handler: NonNull<()>,
    layout: Layout,

    phantom: PhantomData<&'a ()>,
}
```

**Comment by azteca1998** [comment]
Some context:

In the beginning, the `SyscallHandlerMeta` metadata had a generic `<T>` which contained the metadata. This required to pass around another generic to extract the correct meta later on (as in `metadata_storage.get::<SyscallHandlerMeta<T>>()`) which was a pain to code. Also, the generic added a lifetime restriction on the type itself (instead of the values) which we didn't know how to fix. Another reason to not just add the generic is because not all programs may use the syscall handler, and making it a requirement would force everyone to have a dummy implementation (even if it's not instantiable, the type is still required).

Because of that we just replaced that with a pointer (instead of a reference) and a manual lifetime to the object (not the type). The object lifetime should keep the type valid as long as itself is still valid. By removing the lifetime we're no longer forcing that the syscall handler is still available when it's actually used, potentially crashing the program in the best case scenario, or worse: completely corrupting it leaving an impossible mess to debug (ex. the pointer was on the stack and its data is now used by something else).

A potential solution may be to keep the handler allocated within the `SyscallHandlerMeta` itself, while keeping the generic out. This would require probably allocating both the wrapper and the object in a `std::alloca::alloc()` (there's the wrapper already, it may be used as a reference) and having a closure somehow (maybe a `Box<dyn FnOnce()>`) to drop the pointers.

**Comment by azteca1998** [comment]
No longer applicable since we've removed the `SyscallHandlerMeta`.
