### ISSUE TITLE
bug: span issue

### ISSUE THREAD

**Issue by greged93** [lambdaclass/cairo_native#458]
The below is a minimum reproducible example of an issue when passing a `Span` to one function. For some reason, it looks like native drops the first value in the `Span`.
```rust
use crate::common::{compare_outputs, DEFAULT_GAS};
use crate::common::{load_cairo, run_native_program, run_vm_program};
use cairo_lang_runner::SierraCasmRunner;
use cairo_lang_sierra::program::Program;
use lazy_static::lazy_static;

lazy_static! {
    static ref SPAN_ISSUE: (String, Program, SierraCasmRunner) = load_cairo! {
        use array::ArrayTrait;
        use traits::TryInto;
        use core::option::OptionTrait;

        impl TryIntoU8 of TryInto<Span<u8>, u8> {
            fn try_into(self: Span<u8>) -> Option<u8> {
                if self.is_empty() {
                    return Option::None;
                }
                Option::Some(*self.at(0))
            }
        }

        fn run_test() -> u8 {
            let numbers = array![0x2, 0xe4].span();
            numbers.try_into().unwrap()
        }
    };
}

#[test]
fn test_span_issue() {
    let program = &SPAN_ISSUE;
    let result_vm = run_vm_program(program, "run_test", &[], Some(DEFAULT_GAS as usize)).unwrap();
    let result_native =
        run_native_program(program, "run_test", &[], Some(DEFAULT_GAS as u128), None);

    compare_outputs(
        &program.1,
        &program.2.find_function("run_test").unwrap().id,
        &result_vm,
        &result_native,
    )
    .unwrap();
}
```
Expected output as returned by the VM run should be 0x2, but native returns the second value, 0xe4.

**Comment by azteca1998** [comment]
Hello, after some investigating I think I've managed to isolate and understand the issue. It is definitely more interesting and obscure than others, thanks for reporting it.

I've managed to reduce the program to the following:
```cairo
fn main() -> u8 {
    // Span is required (can't reproduce without).
    // Call to is_empty is required (can't reproduce without).
    let x = array![0x02, 0xe4].span();
    let _ = x.is_empty();
    *x.at(0)
}
```

Looking at this we can see that the problem must be related to the `Span<T>` type and the `is_empty()` function. When running on the VM, the span is just a relocatable (or relocatable with length; the point being, it's not an actual clone but a reference). In cairo native though, we don't use segments therefore we can't keep a reference since the data will change, so we clone the data. No big deal there: span clones the data.

Now, as for the `is_empty` method. The method is implemented as follows in the corelib:
```cairo
#[inline(always)]
#[must_use]
fn is_empty(self: Span<T>) -> bool {
    let mut snapshot = self.snapshot;
    match array_snapshot_pop_front(ref snapshot) {
        Option::Some(_) => false,
        Option::None => true,
    }
}
```
We can see that:
  - Takes self by value.
  - Pops the first element. If there was a value then it's not empty.

Initially we might think about why this works in the VM (I sure did), until I noticed the following:
```cairo
impl SpanCopy<T> of Copy<Span<T>>;
```

Remember the spans in the VM which are pointers? The equivalent in rust would be a slice. Slices un rust are copy, as spans are in Cairo. When running on the VM there is no problem because data is immutable, but when running in native we have a bug:
  1. A span is created, which clones the entire array (realloc + memcpy).
  2. The `is_empty` method is called on the span. This causes the span to be copied (not cloned) at Sierra level. In other words, there are now two different spans sharing the same pointer.
  3. The `is_empty` method pops the first element of the span, shifting all the elements in the pointer left once.
  4. When the `is_empty` method returns, the original span still has the same allocated capacity and length, but now the contents are different. The first element is gone and everything else has been shifted. The last element now is undefined behaviour (well, it should contain a copy of the last value, but that's besides the point).
That's why you're getting the second element instead of the first.

Note to self: Check if we are properly freeing allocated memory in `Span<T>`. Since the type also implements drop (getting dropped silently) it's probable that we aren't freeing the memory.

**Comment by greged93** [comment]
Thanks for the explanation! So what would be the solution? Would you have to manually implement `Copy` for all the core lib types that implement it?

**Comment by azteca1998** [comment]
That's one way to do it. I was thinking more about changing the meaning of the internal representation of arrays for snapshots, but I did some testing yesterday and I'm not sure that's possible. If it wasn't possible then I'd need to change both the arrays and array snapshots.

**Comment by greged93** [comment]
hey @azteca1998 any update on the issue?

**Comment by azteca1998** [comment]
Yes, we need to replace both arrays and the spans. I'm rewriting the entire array module. If all goes correctly I should have a fix ready tomorrow or the day after.

**Comment by azteca1998** [comment]
An update: I've been battling a bug in the PR. Basically cloning an array generates an invalid internal structure, which causes the program to either crash with a safety assert we've introduced just in case or segfault directly.

The new representation should be roughly equivalent to the following:
```rs
struct ArrayRepr {
    ptr: *mut (),
    start_offset: u32,
    end_offset: u32,
    capacity: u32,
}
```

The following example illustrates the problem:
```cairo
use array::ArrayTrait;

fn run_test() -> Array<u8> {
    let mut numbers = ArrayTrait::new();
    numbers.clone()
}
```

Here, an array is created, then cloned and the clone is returned. For some reason there's an `inc` (increment) instruction executed that increments `start_offset` when cloning the array. I've made sure it's that instruction by skipping it with the debugger and it passed the test without problems, so I'm pretty sure it's that specific instruction.

As for the MLIR code I've checked multiple times and I haven't found the place where it could generate that instruction. There's some places where the value is incremented (such as pop_front) but the execution shouldn't reach that specific MLIR operation in the example because it only gets executed if the array is not empty.

Of course, the Sierra code doesn't do that either. The clone implementation uses `array_append` and `array_pop_front` but again, `array_append` shouldn't be called when `array_pop_front` returns `None` and the implementation for `array_pop_front` shouldn't increment anything if it has no items.

This leads me to think that it's a bug in either MLIR or LLVM but I haven't been able to confirm that yet.

**Comment by greged93** [comment]
Thanks for the update! I don't know if I can be of any help here but let me know if I can do anything to try to solve this.

**Comment by azteca1998** [comment]
Another update:
  - It turns out that the bug I found earlier while trying to fix the test wasn't related to the test.
  - The test ran `array_new`, `array_get`, `array_pop_front` and `array_append` directly, but the bug wasn't there either. It was in my implementation of `snapshot_take`, which was added implicitly by the Cairo compiler. It has already been fixed.
  - I'll continue fixing the remaining failing tests and mark this PR as ready so we're no longer blocking you, then I'll tackle the clone bug again (unless I get a different task with higher priority, of course).

It turns out that the test was failing because we were doing the equivalent to this (in C)
```c
void *src_ptr = ((void *)ptr) + start_offset;
memcpy(dst_ptr, src_ptr, length);
```
instead of this:
```c
void *src_ptr = ((void *)ptr) + sizeof(elem_ty) * start_offset;
memcpy(dst_ptr, src_ptr, length);
```
