### ISSUE TITLE
Improve the error handling code

### ISSUE THREAD

**Issue by igaray** [lambdaclass/cairo_native#488]
We currently have four implementations of error types in https://github.com/lambdaclass/cairo_native/tree/main/src/error . 
These four error types also overlap somewhat. It would be nicer to have a single `Error` enum type, gathering all error cases into separate variantes, and also removing the `ErrorImpl`.

**Comment by azteca1998** [comment]
For reference, please check out #444.

As for the `ErrorImpl`, It'd be ideal if we had a way to keep the backtrace within the error, since it's more useful for debugging when we have the backtrace of where the error occurred, rather than when the program crashed. But it's alright to remove it for now if it's too complicated since it's nightly-only.

**Comment by hhamud** [comment]
can I take this one @igaray
