### ISSUE TITLE
Error in tx 0x6c51758aa1ae9506602fffb9194da427fe948314b74eb93cdc9570558d4a88d, Killed process

### ISSUE THREAD

**Issue by pefontana** [lambdaclass/cairo_native#722]
When you execute the 0x6c51758aa1ae9506602fffb9194da427fe948314b74eb93cdc9570558d4a88d in starknet-replay, the process gets Killed
In starknet-replay, in a x86 computer
```
cargo run --release tx 0x6c51758aa1ae9506602fffb9194da427fe948314b74eb93cdc9570558d4a88d mainnet 648461
```

```
INFO replay: starting execution
    in replay::transaction with hash: "0x6c51758aa1ae9506602fffb9194da427fe948314b74eb93cdc9570558d4a88d", chain: "mainnet"

Killed
```

**Comment by azteca1998** [comment]
The problem lies in MLIR's canonicalization pass. If you run `mlir-opt --canonicalize contract.mlir` it'll crash with an out of memory.

Disclaimer: Test the bug at your own risk, OOM errors can crash not only themselves but other apps too.
[contract.mlir.txt](https://github.com/user-attachments/files/16113197/contract.mlir.txt)

**Comment by igaray** [comment]
Adding: 
- block: `642001`
- transaction: `0x07666fcaa051e318762020635b0e344fef06bd71f3b05df8ce4e7349b6989345`
- class hash: `0x05b3656430eebda05c8b2722a7e13206d2afb49dcca0be85b545b90f35a3728d `

**Comment by JulianGCalderon** [comment]
llvm-19.1.0-rc2 seems to fix this bug. I tested it by running `mlir-opt` with both contracts mentioned in this issue, and both of them finished successfully

**Comment by pefontana** [comment]
Fixed with https://github.com/lambdaclass/cairo_native/pull/763
